# Project: Airline Reservation System Project
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Airline.o BusinessPassenger.o CharterFlight.o DomesticFlight.o EconomyPassenger.o FirstClassPassenger.o Flight.o InternationalFlight.o Passenger.o Ticket.o
LINKOBJ  = main.o Airline.o BusinessPassenger.o CharterFlight.o DomesticFlight.o EconomyPassenger.o FirstClassPassenger.o Flight.o InternationalFlight.o Passenger.o Ticket.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "Airline Reservation System Project.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Airline.o: Airline.cpp
	$(CPP) -c Airline.cpp -o Airline.o $(CXXFLAGS)

BusinessPassenger.o: BusinessPassenger.cpp
	$(CPP) -c BusinessPassenger.cpp -o BusinessPassenger.o $(CXXFLAGS)

CharterFlight.o: CharterFlight.cpp
	$(CPP) -c CharterFlight.cpp -o CharterFlight.o $(CXXFLAGS)

DomesticFlight.o: DomesticFlight.cpp
	$(CPP) -c DomesticFlight.cpp -o DomesticFlight.o $(CXXFLAGS)

EconomyPassenger.o: EconomyPassenger.cpp
	$(CPP) -c EconomyPassenger.cpp -o EconomyPassenger.o $(CXXFLAGS)

FirstClassPassenger.o: FirstClassPassenger.cpp
	$(CPP) -c FirstClassPassenger.cpp -o FirstClassPassenger.o $(CXXFLAGS)

Flight.o: Flight.cpp
	$(CPP) -c Flight.cpp -o Flight.o $(CXXFLAGS)

InternationalFlight.o: InternationalFlight.cpp
	$(CPP) -c InternationalFlight.cpp -o InternationalFlight.o $(CXXFLAGS)

Passenger.o: Passenger.cpp
	$(CPP) -c Passenger.cpp -o Passenger.o $(CXXFLAGS)

Ticket.o: Ticket.cpp
	$(CPP) -c Ticket.cpp -o Ticket.o $(CXXFLAGS)
